version: "3.11"

services:
  frontend:
    image: frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://backend:8000/
    ports:
      - 3000:3000

  backend:
    image: backend:latest
    ports:
      - 8000:8000
